### ISSUE TITLE
你好，请问这个库基于chromium哪个版本分支？谢谢！

### ISSUE THREAD

**Issue by sweord** [JoKaWare/WTL-DUI#1]
你好，请问这个库基于chromium哪个版本分支？谢谢！

**Comment by JoKaWare** [comment]
版本我都忘记了，时间是11个月前的版本。

------------------ 原始邮件 ------------------
发件人: "sweord";notifications@github.com;
发送时间: 2014年7月22日(星期二) 晚上10:54
收件人: "JoKaWare/WTL-DUI"WTL-DUI@noreply.github.com; 

主题: [WTL-DUI] 你好，请问这个库基于chromium哪个版本分支？谢谢！ (#1)

你好，请问这个库基于chromium哪个版本分支？谢谢！
